# Generated by Django 3.0.5 on 2020-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='value',
        ),
        migrations.AddField(
            model_name='measure',
            name='codigo',
            field=models.CharField(default='1', max_length=40, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='measure',
            name='descripcion',
            field=models.CharField(default='1', max_length=40, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='measure',
            name='nombre',
            field=models.CharField(default='1', max_length=40, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='measure',
            name='prioridad',
            field=models.IntegerField(default='1', max_length=40, verbose_name='prioridad'),
        ),
        migrations.AddField(
            model_name='measure',
            name='tipoIndicador',
            field=models.CharField(default='1', max_length=40, verbose_name='tipoIndicador'),
        ),
    ]
