# Generated by Django 3.0.5 on 2020-05-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20200519_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='prioridad',
            field=models.CharField(default='1', max_length=40, verbose_name='prioridad'),
        ),
    ]
